### ISSUE TITLE
Warning for SameSite attribute on cookies 

### ISSUE THREAD

**Issue by CrowdHailer** [plausible-insights/plausible#35]
![Screenshot from 2020-02-25 05-00-13](https://user-images.githubusercontent.com/5862302/75216441-eeff4980-578b-11ea-950b-1fa7e4cab2fa.png)

I think the image explains the changes needed

**Comment by ukutaht** [comment]
Thanks for reporting. Will fix soon.

**Comment by ukutaht** [comment]
Should be fixed by a315e1c86ca6cbdd49dd73fce0b9c05a8a39c0d7

@CrowdHailer can you confirm?

**Comment by CrowdHailer** [comment]
I still see the issue. Don't know if I should wait for some caches' to clear

**Comment by ukutaht** [comment]
The JS shouldn't be cached for more than a day. Can you take a screenshot of your cookies tab? I only have one cookie with `SameSite=Strict` but admittedly I just cleared my cookies on did.app :)

<img width="1477" alt="Screenshot 2020-02-27 at 15 35 57" src="https://user-images.githubusercontent.com/3731516/75450724-fc792700-5977-11ea-9c94-a5cf12c94928.png">

**Comment by CrowdHailer** [comment]
![Screenshot from 2020-02-27 13-47-50](https://user-images.githubusercontent.com/5862302/75451084-cfbd1380-5967-11ea-905f-107a070c4cca.png)

I seem to have other cookies associated with plausible

**Comment by ukutaht** [comment]
OK. I'm pretty confused about this. The cookie from the tracking script is correctly marked as `SameSite=Strict`. However, it looks like cookies that are set when you visit `plausible.io` are also sent when you include the tracking script on your site. Speicifically, the `_plausible_key` cookie is a phoenix session cookie for your login state on `plausible.io`.

There are also cookies there that absolutely shouldn't be there. Like `_ga` and `amplitude_id`. I have no idea how they got there. 

Not sure how to handle this. I've changed the session cookie on `plausible.io` to include `SameSite=Strict` as well. The session cookie and the cookie from the tracking script are the two cookies that I can control. Can't think of anything else I can do to make Chrome happy in this case.

**Comment by ukutaht** [comment]
I'm closing this as both the tracker cookie and the session cookie on plausible.io both specify the `SameSite` attribute. I'm not sure what's going on with the extra cookies on your device @CrowdHailer but I can't think of anything I can do to fix those.

**Comment by patarapolw** [comment]
I have this issue as well on Nuxt dev-server and Fastify backend ([http-proxy-middleware](https://github.com/nuxt-community/proxy-module) in development).

**Comment by ukutaht** [comment]
@patarapolw Thanks for reporting.

Looks like this has to do with the `logged_in` cookie set when you use the plausible.io service. Fortunately this does not affect your users as the tracking script doesn't set a cookie.

We should still set a SameSite attribute on the `logged_in` cookie as well.
